# backend/seed_data.py
# Run this ONCE: python seed_data.py
from pymongo import MongoClient
from dotenv import load_dotenv
import os

load_dotenv()
client = MongoClient(os.getenv("MONGO_URI"))
db = client["india_tourism"]
db.places.drop()

places = [
    {"id": 1, "name": "Taj Mahal", "city": "Agra", "state": "Uttar Pradesh", "category": "Historical", "rating": 4.9, "entry_fee": 50, "best_time": "Oct - Mar", "duration": "2-3 hours", "description": "One of the Seven Wonders of the World, the Taj Mahal is a white marble mausoleum built by Mughal emperor Shah Jahan in memory of his wife Mumtaz Mahal.", "tags": ["heritage", "history", "romantic"], "lat": 27.1751, "lng": 78.0421, "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1d/Taj_Mahal_%28Edited%29.jpeg/640px-Taj_Mahal_%28Edited%29.jpeg"},
    {"id": 2, "name": "Golden Temple", "city": "Amritsar", "state": "Punjab", "category": "Temple", "rating": 4.9, "entry_fee": 0, "best_time": "Oct - Mar", "duration": "3-4 hours", "description": "The holiest shrine of Sikhism, Harmandir Sahib is covered with 400 kg of gold. Serves free langar to 100,000 people daily.", "tags": ["spiritual", "pilgrimage", "Sikh"], "lat": 31.6200, "lng": 74.8765, "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/94/Golden_Temple%2C_Amritsar%2C_India_-_Aug_2012.jpg/640px-Golden_Temple%2C_Amritsar%2C_India_-_Aug_2012.jpg"},
    {"id": 3, "name": "Alleppey Backwaters", "city": "Alleppey", "state": "Kerala", "category": "Nature", "rating": 4.8, "entry_fee": 0, "best_time": "Oct - Mar", "duration": "Full day", "description": "Known as the Venice of the East, Alleppey backwaters offer houseboat cruises through canals, rivers, and lakes with lush green paddy fields.", "tags": ["backwaters", "houseboat", "nature"], "lat": 9.4981, "lng": 76.3388, "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/08/Alappuzha_backwaters.jpg/640px-Alappuzha_backwaters.jpg"},
    {"id": 4, "name": "Hampi Ruins", "city": "Hampi", "state": "Karnataka", "category": "Historical", "rating": 4.8, "entry_fee": 30, "best_time": "Oct - Feb", "duration": "2-3 days", "description": "A UNESCO World Heritage Site with over 500 monuments of the Vijayanagara Empire including temples, palaces, and market streets.", "tags": ["UNESCO", "ruins", "history"], "lat": 15.3350, "lng": 76.4600, "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/23/Hampi1.jpg/640px-Hampi1.jpg"},
    {"id": 5, "name": "Dal Lake", "city": "Srinagar", "state": "Jammu & Kashmir", "category": "Nature", "rating": 4.8, "entry_fee": 0, "best_time": "Apr - Oct", "duration": "Full day", "description": "Known as the Jewel in the Crown of Kashmir, Dal Lake is famous for its houseboats, shikaras, floating gardens, and mountain views.", "tags": ["lake", "houseboat", "scenic"], "lat": 34.0837, "lng": 74.7973, "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/18/Dal_lake_Srinagar.jpg/640px-Dal_lake_Srinagar.jpg"},
    {"id": 6, "name": "Kaziranga National Park", "city": "Golaghat", "state": "Assam", "category": "National Park", "rating": 4.9, "entry_fee": 500, "best_time": "Nov - Apr", "duration": "2-3 days", "description": "UNESCO World Heritage Site hosting two-thirds of the world's one-horned rhinoceroses. Also home to tigers, elephants, and hundreds of birds.", "tags": ["UNESCO", "rhino", "tiger", "wildlife"], "lat": 26.5775, "lng": 93.1706, "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/Kaziranga_Rhino.jpg/640px-Kaziranga_Rhino.jpg"},
    {"id": 7, "name": "Tirumala Venkateswara Temple", "city": "Tirupati", "state": "Andhra Pradesh", "category": "Temple", "rating": 4.9, "entry_fee": 0, "best_time": "Oct - Mar", "duration": "4-6 hours", "description": "The most visited pilgrimage site in the world receiving 50,000+ devotees daily. Located on Tirumala hills at 853m.", "tags": ["spiritual", "pilgrimage", "temple"], "lat": 13.6833, "lng": 79.3474, "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/50/Tirumala_temple.jpg/640px-Tirumala_temple.jpg"},
    {"id": 8, "name": "Radhanagar Beach", "city": "Havelock Island", "state": "Andaman & Nicobar", "category": "Beach", "rating": 4.9, "entry_fee": 0, "best_time": "Nov - May", "duration": "Full day", "description": "Rated best beach in Asia with pristine white sand, crystal clear turquoise water, and lush forest. Excellent for snorkeling.", "tags": ["beach", "island", "snorkeling", "pristine"], "lat": 11.9877, "lng": 92.9587, "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/72/Radhanagar_Beach.jpg/640px-Radhanagar_Beach.jpg"},
    {"id": 9, "name": "Valley of Flowers", "city": "Chamoli", "state": "Uttarakhand", "category": "National Park", "rating": 4.9, "entry_fee": 150, "best_time": "Jul - Sep", "duration": "3-4 days", "description": "UNESCO World Heritage Site with meadows of 500+ species of alpine wildflowers in the Himalayan valley.", "tags": ["UNESCO", "flowers", "trekking", "nature"], "lat": 30.7280, "lng": 79.6050, "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/62/Valley_of_flowers_trek.jpg/640px-Valley_of_flowers_trek.jpg"},
    {"id": 10, "name": "Rann of Kutch", "city": "Bhuj", "state": "Gujarat", "category": "Nature", "rating": 4.8, "entry_fee": 0, "best_time": "Nov - Feb", "duration": "2-3 days", "description": "World's largest salt desert covering 7500 sq km. During Rann Utsav festival the white desert glows under moonlight.", "tags": ["salt desert", "unique", "festival", "photography"], "lat": 23.7337, "lng": 69.8597, "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b7/Rann_of_Kutch.jpg/640px-Rann_of_Kutch.jpg"},
]

db.places.insert_many(places)
print(f"✅ Inserted {len(places)} places into MongoDB successfully!")